### ISSUE TITLE
图片无法转发

### ISSUE THREAD

**Issue by albertyangx** [idanran/myrtus#20]
文字可以正常转发，图片报错
报错信息如下

[E] forward ReferenceError: FormData is not defined
                            at RedMessageEncoder.image (D:\koishi\data\instances\default\node_modules\koishi-plugin-adapter-red\lib\message.js:94:25)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async RedMessageEncoder.visit (D:\koishi\data\instances\default\node_modules\koishi-plugin-adapter-red\lib\message.js:244:17)
                            at async RedMessageEncoder.render (D:\koishi\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:545:7)
                            at async RedMessageEncoder.visit (D:\koishi\data\instances\default\node_modules\koishi-plugin-adapter-red\lib\message.js:309:17)
                            at async RedMessageEncoder.render (D:\koishi\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:545:7)
                            at async RedMessageEncoder.send (D:\koishi\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:577:5)
                            at async RedBot.sendMessage (D:\koishi\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:339:22)
                            at async Proxy.<anonymous> (D:\koishi\data\instances\default\node_modules\@myrtus\koishi-plugin-forward\lib\core.js:165:40)

**Comment by idanran** [comment]
如果你在使用 koishi desktop 的话，请将其更新至 1.0.1，否则请更新 node 至最新 LTS。

**Comment by albertyangx** [comment]
Windows koishi desktop 更新至1.0.1解决上述问题

感谢大佬！
